syntax = "proto3";
package cometbft.multiplex.v1;

option go_package = "github.com/ice-blockchain/cometbft/api/cometbft/multiplex/v1";

import "gogoproto/gogo.proto";

// AckTransactionBroadcast acknowledges the broadcast of a transaction batch.
message AckTransactionBroadcast {
  bytes tx_hash   = 1;
  string node_id  = 2;
  string chain_id = 3 [(gogoproto.customname) = "ChainID"];
}

// Receipt is an abstract receipt message.
message Receipt {
  // Sum of all possible messages.
  oneof sum {
    AckTransactionBroadcast ack_transaction_broadcast = 1;
  }
}
