syntax = "proto3";
package cometbft.multiplex.v1;

option go_package = "github.com/ice-blockchain/cometbft/api/cometbft/multiplex/v1";

import "gogoproto/gogo.proto";
import "cometbft/p2p/v1/types.proto";

// MultiNetworkNodeInfo is the node information exchanged between two
// peers of a multi-network infra during the CometBFT P2P handshake.
message MultiNetworkNodeInfo {
  cometbft.p2p.v1.ProtocolVersion protocol_version = 1;

  string                   default_node_id   = 2 [(gogoproto.customname) = "DefaultNodeID"];
  string                   listen_addr       = 3;
  string                   version           = 4;
  bytes                    channels          = 5;
  string                   moniker           = 6;
  cometbft.p2p.v1.DefaultNodeInfoOther other = 7 [(gogoproto.nullable) = false];
}
