// Code generated by metricsgen. DO NOT EDIT.

package multiplex

import (
	"github.com/ice-blockchain/cometbft/libs/metrics/discard"
	prometheus "github.com/ice-blockchain/cometbft/libs/metrics/prometheus"
	stdprometheus "github.com/prometheus/client_golang/prometheus"
)

func PrometheusMetrics(namespace string, labelsAndValues ...string) *Metrics {
	labels := []string{}
	for i := 0; i < len(labelsAndValues); i += 2 {
		labels = append(labels, labelsAndValues[i])
	}
	return &Metrics{
		ProcessorUsage: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "cpu_usage",
			Help:      "Histogram of CPU load percentage.",

			Buckets: stdprometheus.LinearBuckets(10, 10, 10),
		}, labels).With(labelsAndValues...),
		MemoryUsage: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "ram_usage",
			Help:      "Histogram of total allocated bytes (RAM).",

			Buckets: stdprometheus.ExponentialBuckets(1, 3, 7),
		}, labels).With(labelsAndValues...),
		TotalNetworkBytes: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "bandwidth_usage",
			Help:      "Histogram of bandwidth usage in bytes across all networks.",

			Buckets: stdprometheus.ExponentialBuckets(1, 3, 7),
		}, labels).With(labelsAndValues...),
		TotalBlocks: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "total_blocks",
			Help:      "Total number of committed blocks across all networks.",
		}, labels).With(labelsAndValues...),
		// TotalBlocksPerUser: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
		// 	Namespace: namespace,
		// 	Subsystem: MetricsSubsystem,
		// 	Name:      "total_blocks_user",
		// 	Help:      "Total number of committed blocks by each user.",
		// }, labels).With(labelsAndValues...),
		TotalTxs: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "total_txs",
			Help:      "Total number of committed transactions across all networks.",
		}, labels).With(labelsAndValues...),
		// TotalTxsPerUser: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
		// 	Namespace: namespace,
		// 	Subsystem: MetricsSubsystem,
		// 	Name:      "total_txs_user",
		// 	Help:      "Total number of committed transactions by each user.",
		// }, labels).With(labelsAndValues...),
		InitDurationSeconds: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "init_duration_seconds",
			Help:      "Histogram of relay initialization.",

			Buckets: stdprometheus.ExponentialBuckets(0.0002, 10, 7),
		}, labels).With(labelsAndValues...),
		StartDurationSeconds: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "start_duration_seconds",
			Help:      "Histogram of relay initialization.",

			Buckets: stdprometheus.ExponentialBuckets(0.0002, 10, 8),
		}, labels).With(labelsAndValues...),
		Errors: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "errors",
			Help:      "Total number of errors caught.",
		}, labels).With(labelsAndValues...),
		// ErrorsPerUser: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
		// 	Namespace: namespace,
		// 	Subsystem: MetricsSubsystem,
		// 	Name:      "errors_user",
		// 	Help:      "Total number of errors caught by each user.",
		// }, labels).With(labelsAndValues...),
	}
}

func NopMetrics() *Metrics {
	return &Metrics{
		ProcessorUsage:    discard.NewHistogram(),
		MemoryUsage:       discard.NewHistogram(),
		TotalNetworkBytes: discard.NewHistogram(),
		TotalBlocks:       discard.NewGauge(),
		// TotalBlocksPerUser:   discard.NewGauge(),
		TotalTxs: discard.NewGauge(),
		// TotalTxsPerUser:      discard.NewGauge(),
		InitDurationSeconds:  discard.NewHistogram(),
		StartDurationSeconds: discard.NewHistogram(),
		Errors:               discard.NewCounter(),
		// ErrorsPerUser:        discard.NewCounter(),
	}
}
