// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cometbft/multiplex/v1/messages.proto

package v1

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	v1 "github.com/ice-blockchain/cometbft/api/cometbft/types/v1"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ChainParams contains the parameters needed to connect to one chain.
type ChainParams struct {
	GenesisTime     time.Time           `protobuf:"bytes,1,opt,name=genesis_time,json=genesisTime,proto3,stdtime" json:"genesis_time"`
	ChainID         string              `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ConsensusParams *v1.ConsensusParams `protobuf:"bytes,3,opt,name=consensus_params,json=consensusParams,proto3" json:"consensus_params,omitempty"`
	Validators      v1.ValidatorSet     `protobuf:"bytes,4,opt,name=validators,proto3" json:"validators"`
	AppHash         []byte              `protobuf:"bytes,5,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	AppStateBytes   []byte              `protobuf:"bytes,6,opt,name=app_state_bytes,json=appStateBytes,proto3" json:"app_state_bytes,omitempty"`
	InitialHeight   int64               `protobuf:"varint,7,opt,name=initial_height,json=initialHeight,proto3" json:"initial_height,omitempty"`
}

func (m *ChainParams) Reset()         { *m = ChainParams{} }
func (m *ChainParams) String() string { return proto.CompactTextString(m) }
func (*ChainParams) ProtoMessage()    {}
func (*ChainParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_4667fdf2be658734, []int{0}
}
func (m *ChainParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainParams.Merge(m, src)
}
func (m *ChainParams) XXX_Size() int {
	return m.Size()
}
func (m *ChainParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainParams.DiscardUnknown(m)
}

var xxx_messageInfo_ChainParams proto.InternalMessageInfo

func (m *ChainParams) GetGenesisTime() time.Time {
	if m != nil {
		return m.GenesisTime
	}
	return time.Time{}
}

func (m *ChainParams) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *ChainParams) GetConsensusParams() *v1.ConsensusParams {
	if m != nil {
		return m.ConsensusParams
	}
	return nil
}

func (m *ChainParams) GetValidators() v1.ValidatorSet {
	if m != nil {
		return m.Validators
	}
	return v1.ValidatorSet{}
}

func (m *ChainParams) GetAppHash() []byte {
	if m != nil {
		return m.AppHash
	}
	return nil
}

func (m *ChainParams) GetAppStateBytes() []byte {
	if m != nil {
		return m.AppStateBytes
	}
	return nil
}

func (m *ChainParams) GetInitialHeight() int64 {
	if m != nil {
		return m.InitialHeight
	}
	return 0
}

// ChainReplicationRequest requests to replicate a new chain with replication details.
type ChainReplicationRequest struct {
	ChainID     string       `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainParams *ChainParams `protobuf:"bytes,2,opt,name=chain_params,json=chainParams,proto3" json:"chain_params,omitempty"`
}

func (m *ChainReplicationRequest) Reset()         { *m = ChainReplicationRequest{} }
func (m *ChainReplicationRequest) String() string { return proto.CompactTextString(m) }
func (*ChainReplicationRequest) ProtoMessage()    {}
func (*ChainReplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4667fdf2be658734, []int{1}
}
func (m *ChainReplicationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainReplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainReplicationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainReplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainReplicationRequest.Merge(m, src)
}
func (m *ChainReplicationRequest) XXX_Size() int {
	return m.Size()
}
func (m *ChainReplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainReplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChainReplicationRequest proto.InternalMessageInfo

func (m *ChainReplicationRequest) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *ChainReplicationRequest) GetChainParams() *ChainParams {
	if m != nil {
		return m.ChainParams
	}
	return nil
}

// ChainReplicationResponse acknowledges the replication of a new chain.
type ChainReplicationResponse struct {
	ChainID string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	NodeId  string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (m *ChainReplicationResponse) Reset()         { *m = ChainReplicationResponse{} }
func (m *ChainReplicationResponse) String() string { return proto.CompactTextString(m) }
func (*ChainReplicationResponse) ProtoMessage()    {}
func (*ChainReplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4667fdf2be658734, []int{2}
}
func (m *ChainReplicationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainReplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainReplicationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainReplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainReplicationResponse.Merge(m, src)
}
func (m *ChainReplicationResponse) XXX_Size() int {
	return m.Size()
}
func (m *ChainReplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainReplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChainReplicationResponse proto.InternalMessageInfo

func (m *ChainReplicationResponse) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *ChainReplicationResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

// AckTransactionBroadcast acknowledges the broadcast of a transaction batch.
type AckTransactionBroadcast struct {
	TxHashes [][]byte `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
}

func (m *AckTransactionBroadcast) Reset()         { *m = AckTransactionBroadcast{} }
func (m *AckTransactionBroadcast) String() string { return proto.CompactTextString(m) }
func (*AckTransactionBroadcast) ProtoMessage()    {}
func (*AckTransactionBroadcast) Descriptor() ([]byte, []int) {
	return fileDescriptor_4667fdf2be658734, []int{3}
}
func (m *AckTransactionBroadcast) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AckTransactionBroadcast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AckTransactionBroadcast.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AckTransactionBroadcast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckTransactionBroadcast.Merge(m, src)
}
func (m *AckTransactionBroadcast) XXX_Size() int {
	return m.Size()
}
func (m *AckTransactionBroadcast) XXX_DiscardUnknown() {
	xxx_messageInfo_AckTransactionBroadcast.DiscardUnknown(m)
}

var xxx_messageInfo_AckTransactionBroadcast proto.InternalMessageInfo

func (m *AckTransactionBroadcast) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

// Message is an abstract multiplex message.
type Message struct {
	// Sum of all possible messages.
	//
	// Types that are valid to be assigned to Sum:
	//
	//	*Message_ChainReplicationRequest
	//	*Message_ChainReplicationResponse
	//	*Message_AckTransactionBroadcast
	Sum isMessage_Sum `protobuf_oneof:"sum"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4667fdf2be658734, []int{4}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Sum interface {
	isMessage_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Message_ChainReplicationRequest struct {
	ChainReplicationRequest *ChainReplicationRequest `protobuf:"bytes,1,opt,name=chain_replication_request,json=chainReplicationRequest,proto3,oneof" json:"chain_replication_request,omitempty"`
}
type Message_ChainReplicationResponse struct {
	ChainReplicationResponse *ChainReplicationResponse `protobuf:"bytes,2,opt,name=chain_replication_response,json=chainReplicationResponse,proto3,oneof" json:"chain_replication_response,omitempty"`
}
type Message_AckTransactionBroadcast struct {
	AckTransactionBroadcast *AckTransactionBroadcast `protobuf:"bytes,3,opt,name=ack_transaction_broadcast,json=ackTransactionBroadcast,proto3,oneof" json:"ack_transaction_broadcast,omitempty"`
}

func (*Message_ChainReplicationRequest) isMessage_Sum()  {}
func (*Message_ChainReplicationResponse) isMessage_Sum() {}
func (*Message_AckTransactionBroadcast) isMessage_Sum()  {}

func (m *Message) GetSum() isMessage_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *Message) GetChainReplicationRequest() *ChainReplicationRequest {
	if x, ok := m.GetSum().(*Message_ChainReplicationRequest); ok {
		return x.ChainReplicationRequest
	}
	return nil
}

func (m *Message) GetChainReplicationResponse() *ChainReplicationResponse {
	if x, ok := m.GetSum().(*Message_ChainReplicationResponse); ok {
		return x.ChainReplicationResponse
	}
	return nil
}

func (m *Message) GetAckTransactionBroadcast() *AckTransactionBroadcast {
	if x, ok := m.GetSum().(*Message_AckTransactionBroadcast); ok {
		return x.AckTransactionBroadcast
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_ChainReplicationRequest)(nil),
		(*Message_ChainReplicationResponse)(nil),
		(*Message_AckTransactionBroadcast)(nil),
	}
}

func init() {
	proto.RegisterType((*ChainParams)(nil), "cometbft.multiplex.v1.ChainParams")
	proto.RegisterType((*ChainReplicationRequest)(nil), "cometbft.multiplex.v1.ChainReplicationRequest")
	proto.RegisterType((*ChainReplicationResponse)(nil), "cometbft.multiplex.v1.ChainReplicationResponse")
	proto.RegisterType((*AckTransactionBroadcast)(nil), "cometbft.multiplex.v1.AckTransactionBroadcast")
	proto.RegisterType((*Message)(nil), "cometbft.multiplex.v1.Message")
}

func init() {
	proto.RegisterFile("cometbft/multiplex/v1/messages.proto", fileDescriptor_4667fdf2be658734)
}

var fileDescriptor_4667fdf2be658734 = []byte{
	// 632 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x41, 0x4f, 0xdb, 0x30,
	0x18, 0x86, 0x9b, 0x16, 0x68, 0x71, 0xcb, 0x98, 0xa2, 0x4d, 0x0d, 0x9d, 0x94, 0x76, 0xd5, 0x86,
	0x7a, 0x59, 0x22, 0x36, 0x69, 0xa7, 0x5d, 0x16, 0x86, 0x56, 0x0e, 0x48, 0x93, 0x41, 0x1c, 0xb6,
	0x43, 0xe4, 0xb8, 0x26, 0xb1, 0x48, 0x62, 0x2f, 0x76, 0x2b, 0xf8, 0x07, 0x3b, 0xf2, 0xb3, 0x38,
	0x72, 0xdc, 0x65, 0x6c, 0x2a, 0xff, 0x63, 0x9a, 0xec, 0xa4, 0x01, 0xd6, 0x16, 0x71, 0x8b, 0x3f,
	0xbf, 0xfe, 0xde, 0xf7, 0x7b, 0x92, 0x18, 0xbc, 0xc2, 0x2c, 0x21, 0x32, 0x38, 0x91, 0x6e, 0x32,
	0x8e, 0x25, 0xe5, 0x31, 0x39, 0x73, 0x27, 0x3b, 0x6e, 0x42, 0x84, 0x40, 0x21, 0x11, 0x0e, 0xcf,
	0x98, 0x64, 0xe6, 0xf3, 0x99, 0xca, 0x29, 0x55, 0xce, 0x64, 0xa7, 0xf3, 0x2c, 0x64, 0x21, 0xd3,
	0x0a, 0x57, 0x3d, 0xe5, 0xe2, 0x4e, 0x37, 0x64, 0x2c, 0x8c, 0x89, 0xab, 0x57, 0xc1, 0xf8, 0xc4,
	0x95, 0x34, 0x21, 0x42, 0xa2, 0x84, 0x17, 0x82, 0x97, 0xa5, 0xa7, 0x3c, 0xe7, 0x44, 0x28, 0xbf,
	0x09, 0x8a, 0xe9, 0x08, 0x49, 0x96, 0x15, 0x12, 0x7b, 0x5e, 0xc2, 0x51, 0x86, 0x92, 0x22, 0x50,
	0xff, 0x6f, 0x15, 0x34, 0x77, 0x23, 0x44, 0xd3, 0x2f, 0xba, 0x6a, 0x7e, 0x06, 0xad, 0x90, 0xa4,
	0x44, 0x50, 0xe1, 0x2b, 0x37, 0xcb, 0xe8, 0x19, 0x83, 0xe6, 0xdb, 0x8e, 0x93, 0x47, 0x71, 0x66,
	0x51, 0x9c, 0xa3, 0x59, 0x14, 0xaf, 0x71, 0x79, 0xdd, 0xad, 0x5c, 0xfc, 0xee, 0x1a, 0xb0, 0x59,
	0x9c, 0x54, 0x7b, 0xe6, 0x36, 0x68, 0x60, 0xd5, 0xd7, 0xa7, 0x23, 0xab, 0xda, 0x33, 0x06, 0xeb,
	0x5e, 0x73, 0x7a, 0xdd, 0xad, 0x6b, 0xaf, 0xfd, 0x4f, 0xb0, 0xae, 0x37, 0xf7, 0x47, 0xe6, 0x01,
	0x78, 0x8a, 0x59, 0x2a, 0x48, 0x2a, 0xc6, 0xc2, 0xcf, 0xa3, 0x59, 0x35, 0x6d, 0xda, 0x77, 0x4a,
	0x58, 0x3a, 0xbb, 0x33, 0xd9, 0x71, 0x76, 0x67, 0xd2, 0x3c, 0x2e, 0xdc, 0xc4, 0xf7, 0x0b, 0xe6,
	0x1e, 0x00, 0x25, 0x02, 0x61, 0xad, 0xe8, 0x46, 0xdd, 0x05, 0x8d, 0x8e, 0x67, 0xa2, 0x43, 0x22,
	0xbd, 0x15, 0x35, 0x02, 0xbc, 0x73, 0xd0, 0xdc, 0x02, 0x0d, 0xc4, 0xb9, 0x1f, 0x21, 0x11, 0x59,
	0xab, 0x3d, 0x63, 0xd0, 0x82, 0x75, 0xc4, 0xf9, 0x10, 0x89, 0xc8, 0xdc, 0x06, 0x9b, 0x6a, 0x4b,
	0x48, 0x24, 0x89, 0x1f, 0x9c, 0x4b, 0x22, 0xac, 0x35, 0xad, 0xd8, 0x40, 0x9c, 0x1f, 0xaa, 0xaa,
	0xa7, 0x8a, 0xe6, 0x6b, 0xf0, 0x84, 0xa6, 0x54, 0x52, 0x14, 0xfb, 0x11, 0xa1, 0x61, 0x24, 0xad,
	0x7a, 0xcf, 0x18, 0xd4, 0xe0, 0x46, 0x51, 0x1d, 0xea, 0x62, 0xff, 0x87, 0x01, 0xda, 0x1a, 0x0a,
	0x24, 0x3c, 0xa6, 0x18, 0x49, 0xca, 0x52, 0x48, 0xbe, 0x8f, 0x89, 0x90, 0xf7, 0x18, 0x1a, 0x0f,
	0x30, 0xdc, 0x03, 0xad, 0x5c, 0x57, 0xf0, 0xab, 0xfe, 0xcf, 0xef, 0xee, 0xc7, 0xe6, 0xdc, 0x79,
	0xdd, 0xb0, 0x89, 0x6f, 0x17, 0xfd, 0x6f, 0xc0, 0x9a, 0x4f, 0x22, 0xb8, 0x22, 0xfc, 0xe8, 0x28,
	0x6d, 0x50, 0x4f, 0xd9, 0x88, 0x94, 0x6f, 0x1d, 0xae, 0xa9, 0xe5, 0xfe, 0xa8, 0xff, 0x1e, 0xb4,
	0x3f, 0xe2, 0xd3, 0xa3, 0x0c, 0xa5, 0x02, 0x61, 0xd5, 0xda, 0xcb, 0x18, 0x1a, 0x61, 0x24, 0xa4,
	0xf9, 0x02, 0xac, 0xcb, 0x33, 0xcd, 0x9a, 0x08, 0xcb, 0xe8, 0xd5, 0x06, 0x2d, 0xd8, 0x90, 0x67,
	0x43, 0xbd, 0xee, 0xff, 0xaa, 0x82, 0xfa, 0x41, 0xfe, 0x13, 0x99, 0x31, 0xd8, 0xca, 0x43, 0x64,
	0xb7, 0x09, 0xfd, 0x2c, 0x87, 0x55, 0x7c, 0xa9, 0xce, 0x43, 0x43, 0xcf, 0x23, 0x1e, 0x56, 0x60,
	0x1b, 0x2f, 0xa1, 0xcf, 0x40, 0x67, 0x91, 0x5b, 0x0e, 0xa4, 0x60, 0xec, 0x3e, 0xda, 0x2e, 0x3f,
	0x36, 0xac, 0x40, 0x0b, 0x2f, 0x63, 0x1c, 0x83, 0x2d, 0x84, 0x4f, 0x7d, 0x79, 0xcb, 0xc8, 0x0f,
	0x66, 0x90, 0x8a, 0x7f, 0x62, 0xd9, 0x78, 0x4b, 0xd0, 0xaa, 0xf1, 0xd0, 0xe2, 0x2d, 0x6f, 0x15,
	0xd4, 0xc4, 0x38, 0xf1, 0x8e, 0x2f, 0xa7, 0xb6, 0x71, 0x35, 0xb5, 0x8d, 0x3f, 0x53, 0xdb, 0xb8,
	0xb8, 0xb1, 0x2b, 0x57, 0x37, 0x76, 0xe5, 0xe7, 0x8d, 0x5d, 0xf9, 0xfa, 0x21, 0xa4, 0x32, 0x1a,
	0x07, 0xca, 0xd1, 0xa5, 0x98, 0xbc, 0x09, 0x62, 0x86, 0x4f, 0x75, 0x78, 0xb7, 0xbc, 0x54, 0x10,
	0xa7, 0xee, 0xc2, 0x8b, 0x2f, 0x58, 0xd3, 0x57, 0xc5, 0xbb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x58, 0x7a, 0xfc, 0xe4, 0x18, 0x05, 0x00, 0x00,
}

func (m *ChainParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InitialHeight != 0 {
		i = encodeVarintMessages(dAtA, i, uint64(m.InitialHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.AppStateBytes) > 0 {
		i -= len(m.AppStateBytes)
		copy(dAtA[i:], m.AppStateBytes)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.AppStateBytes)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AppHash) > 0 {
		i -= len(m.AppHash)
		copy(dAtA[i:], m.AppHash)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.AppHash)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.Validators.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMessages(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.ConsensusParams != nil {
		{
			size, err := m.ConsensusParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessages(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0x12
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.GenesisTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.GenesisTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintMessages(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ChainReplicationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainReplicationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainReplicationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ChainParams != nil {
		{
			size, err := m.ChainParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessages(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ChainReplicationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainReplicationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainReplicationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintMessages(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AckTransactionBroadcast) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AckTransactionBroadcast) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AckTransactionBroadcast) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxHashes) > 0 {
		for iNdEx := len(m.TxHashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TxHashes[iNdEx])
			copy(dAtA[i:], m.TxHashes[iNdEx])
			i = encodeVarintMessages(dAtA, i, uint64(len(m.TxHashes[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sum != nil {
		{
			size := m.Sum.Size()
			i -= size
			if _, err := m.Sum.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *Message_ChainReplicationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_ChainReplicationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ChainReplicationRequest != nil {
		{
			size, err := m.ChainReplicationRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessages(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *Message_ChainReplicationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_ChainReplicationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ChainReplicationResponse != nil {
		{
			size, err := m.ChainReplicationResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessages(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *Message_AckTransactionBroadcast) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message_AckTransactionBroadcast) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.AckTransactionBroadcast != nil {
		{
			size, err := m.AckTransactionBroadcast.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessages(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func encodeVarintMessages(dAtA []byte, offset int, v uint64) int {
	offset -= sovMessages(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ChainParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.GenesisTime)
	n += 1 + l + sovMessages(uint64(l))
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	if m.ConsensusParams != nil {
		l = m.ConsensusParams.Size()
		n += 1 + l + sovMessages(uint64(l))
	}
	l = m.Validators.Size()
	n += 1 + l + sovMessages(uint64(l))
	l = len(m.AppHash)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	l = len(m.AppStateBytes)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	if m.InitialHeight != 0 {
		n += 1 + sovMessages(uint64(m.InitialHeight))
	}
	return n
}

func (m *ChainReplicationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	if m.ChainParams != nil {
		l = m.ChainParams.Size()
		n += 1 + l + sovMessages(uint64(l))
	}
	return n
}

func (m *ChainReplicationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovMessages(uint64(l))
	}
	return n
}

func (m *AckTransactionBroadcast) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TxHashes) > 0 {
		for _, b := range m.TxHashes {
			l = len(b)
			n += 1 + l + sovMessages(uint64(l))
		}
	}
	return n
}

func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sum != nil {
		n += m.Sum.Size()
	}
	return n
}

func (m *Message_ChainReplicationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainReplicationRequest != nil {
		l = m.ChainReplicationRequest.Size()
		n += 1 + l + sovMessages(uint64(l))
	}
	return n
}
func (m *Message_ChainReplicationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainReplicationResponse != nil {
		l = m.ChainReplicationResponse.Size()
		n += 1 + l + sovMessages(uint64(l))
	}
	return n
}
func (m *Message_AckTransactionBroadcast) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AckTransactionBroadcast != nil {
		l = m.AckTransactionBroadcast.Size()
		n += 1 + l + sovMessages(uint64(l))
	}
	return n
}

func sovMessages(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessages(x uint64) (n int) {
	return sovMessages(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChainParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.GenesisTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusParams == nil {
				m.ConsensusParams = &v1.ConsensusParams{}
			}
			if err := m.ConsensusParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Validators.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppHash = append(m.AppHash[:0], dAtA[iNdEx:postIndex]...)
			if m.AppHash == nil {
				m.AppHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppStateBytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppStateBytes = append(m.AppStateBytes[:0], dAtA[iNdEx:postIndex]...)
			if m.AppStateBytes == nil {
				m.AppStateBytes = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialHeight", wireType)
			}
			m.InitialHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChainReplicationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainReplicationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainReplicationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ChainParams == nil {
				m.ChainParams = &ChainParams{}
			}
			if err := m.ChainParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChainReplicationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainReplicationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainReplicationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AckTransactionBroadcast) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AckTransactionBroadcast: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AckTransactionBroadcast: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHashes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHashes = append(m.TxHashes, make([]byte, postIndex-iNdEx))
			copy(m.TxHashes[len(m.TxHashes)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainReplicationRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ChainReplicationRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Message_ChainReplicationRequest{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainReplicationResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ChainReplicationResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Message_ChainReplicationResponse{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AckTransactionBroadcast", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessages
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessages
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AckTransactionBroadcast{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Message_AckTransactionBroadcast{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessages(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessages
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessages
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMessages
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMessages
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMessages        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessages          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMessages = fmt.Errorf("proto: unexpected end of group")
)
