// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cometbft/multiplex/v1/receipts.proto

package v1

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AckTransactionBroadcast acknowledges the broadcast of a transaction batch.
type AckTransactionBroadcast struct {
	TxHashes [][]byte `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
	NodeId   string   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ChainID  string   `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
}

func (m *AckTransactionBroadcast) Reset()         { *m = AckTransactionBroadcast{} }
func (m *AckTransactionBroadcast) String() string { return proto.CompactTextString(m) }
func (*AckTransactionBroadcast) ProtoMessage()    {}
func (*AckTransactionBroadcast) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f6e9f69ca3e462, []int{0}
}
func (m *AckTransactionBroadcast) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AckTransactionBroadcast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AckTransactionBroadcast.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AckTransactionBroadcast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckTransactionBroadcast.Merge(m, src)
}
func (m *AckTransactionBroadcast) XXX_Size() int {
	return m.Size()
}
func (m *AckTransactionBroadcast) XXX_DiscardUnknown() {
	xxx_messageInfo_AckTransactionBroadcast.DiscardUnknown(m)
}

var xxx_messageInfo_AckTransactionBroadcast proto.InternalMessageInfo

func (m *AckTransactionBroadcast) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func (m *AckTransactionBroadcast) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *AckTransactionBroadcast) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

// Receipt is an abstract receipt message.
type Receipt struct {
	// Sum of all possible messages.
	//
	// Types that are valid to be assigned to Sum:
	//
	//	*Receipt_AckTransactionBroadcast
	Sum isReceipt_Sum `protobuf_oneof:"sum"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f6e9f69ca3e462, []int{1}
}
func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return m.Size()
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

type isReceipt_Sum interface {
	isReceipt_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Receipt_AckTransactionBroadcast struct {
	AckTransactionBroadcast *AckTransactionBroadcast `protobuf:"bytes,1,opt,name=ack_transaction_broadcast,json=ackTransactionBroadcast,proto3,oneof" json:"ack_transaction_broadcast,omitempty"`
}

func (*Receipt_AckTransactionBroadcast) isReceipt_Sum() {}

func (m *Receipt) GetSum() isReceipt_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *Receipt) GetAckTransactionBroadcast() *AckTransactionBroadcast {
	if x, ok := m.GetSum().(*Receipt_AckTransactionBroadcast); ok {
		return x.AckTransactionBroadcast
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Receipt) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Receipt_AckTransactionBroadcast)(nil),
	}
}

func init() {
	proto.RegisterType((*AckTransactionBroadcast)(nil), "cometbft.multiplex.v1.AckTransactionBroadcast")
	proto.RegisterType((*Receipt)(nil), "cometbft.multiplex.v1.Receipt")
}

func init() {
	proto.RegisterFile("cometbft/multiplex/v1/receipts.proto", fileDescriptor_75f6e9f69ca3e462)
}

var fileDescriptor_75f6e9f69ca3e462 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x45, 0x63, 0x2a, 0x9a, 0xd6, 0x65, 0x8a, 0x40, 0x2d, 0x20, 0x99, 0xaa, 0x42, 0xa8, 0x0b,
	0xb6, 0x0a, 0x2b, 0x0b, 0x81, 0xa1, 0x5d, 0x23, 0xc4, 0xc0, 0x12, 0x39, 0x8e, 0x69, 0xac, 0x26,
	0x71, 0x14, 0x3b, 0x25, 0x13, 0xdf, 0xc0, 0x67, 0x31, 0x76, 0x64, 0x42, 0x28, 0xf9, 0x11, 0xe4,
	0x54, 0x2d, 0x4b, 0xd8, 0xfc, 0x7c, 0x8f, 0xe4, 0xe3, 0xfb, 0xe0, 0x25, 0x93, 0x09, 0xd7, 0xc1,
	0xab, 0x26, 0x49, 0x11, 0x6b, 0x91, 0xc5, 0xbc, 0x24, 0xeb, 0x19, 0xc9, 0x39, 0xe3, 0x22, 0xd3,
	0x0a, 0x67, 0xb9, 0xd4, 0xd2, 0x39, 0xd9, 0x51, 0x78, 0x4f, 0xe1, 0xf5, 0xec, 0xec, 0x78, 0x29,
	0x97, 0xb2, 0x21, 0x88, 0x39, 0x6d, 0xe1, 0xc9, 0x1b, 0x1c, 0xde, 0xb3, 0xd5, 0x53, 0x4e, 0x53,
	0x45, 0x99, 0x16, 0x32, 0x75, 0x73, 0x49, 0x43, 0x46, 0x95, 0x76, 0xce, 0x61, 0x5f, 0x97, 0x7e,
	0x44, 0x55, 0xc4, 0xd5, 0x08, 0x8c, 0x3b, 0xd3, 0x23, 0xaf, 0xa7, 0xcb, 0x79, 0x33, 0x3b, 0x43,
	0x68, 0xa7, 0x32, 0xe4, 0xbe, 0x08, 0x47, 0x07, 0x63, 0x30, 0xed, 0x7b, 0x5d, 0x33, 0x2e, 0x42,
	0xe7, 0x0a, 0xf6, 0x58, 0x44, 0x45, 0x6a, 0x92, 0x8e, 0x49, 0xdc, 0x41, 0xf5, 0x7d, 0x61, 0x3f,
	0x98, 0xbb, 0xc5, 0xa3, 0x67, 0x37, 0xe1, 0x22, 0x9c, 0xbc, 0x43, 0xdb, 0xdb, 0x7a, 0x3b, 0x31,
	0x3c, 0xa5, 0x6c, 0xe5, 0xeb, 0x3f, 0x09, 0x3f, 0xd8, 0x59, 0x8c, 0xc0, 0x18, 0x4c, 0x07, 0x37,
	0x18, 0xb7, 0x7e, 0x0a, 0xff, 0xe3, 0x3e, 0xb7, 0xbc, 0x21, 0x6d, 0x8f, 0xdc, 0x43, 0xd8, 0x51,
	0x45, 0xe2, 0x3e, 0x7f, 0x56, 0x08, 0x6c, 0x2a, 0x04, 0x7e, 0x2a, 0x04, 0x3e, 0x6a, 0x64, 0x6d,
	0x6a, 0x64, 0x7d, 0xd5, 0xc8, 0x7a, 0xb9, 0x5b, 0x0a, 0x1d, 0x15, 0x81, 0x79, 0x91, 0x08, 0xc6,
	0xaf, 0x83, 0x58, 0xb2, 0x55, 0xa3, 0x4d, 0xf6, 0xfd, 0xd3, 0x4c, 0x90, 0xd6, 0x65, 0x04, 0xdd,
	0xa6, 0xd7, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xdd, 0x61, 0x1a, 0xac, 0x01, 0x00,
	0x00,
}

func (m *AckTransactionBroadcast) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AckTransactionBroadcast) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AckTransactionBroadcast) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintReceipts(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintReceipts(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxHashes) > 0 {
		for iNdEx := len(m.TxHashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TxHashes[iNdEx])
			copy(dAtA[i:], m.TxHashes[iNdEx])
			i = encodeVarintReceipts(dAtA, i, uint64(len(m.TxHashes[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Receipt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Receipt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Receipt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sum != nil {
		{
			size := m.Sum.Size()
			i -= size
			if _, err := m.Sum.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *Receipt_AckTransactionBroadcast) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Receipt_AckTransactionBroadcast) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.AckTransactionBroadcast != nil {
		{
			size, err := m.AckTransactionBroadcast.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintReceipts(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func encodeVarintReceipts(dAtA []byte, offset int, v uint64) int {
	offset -= sovReceipts(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AckTransactionBroadcast) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TxHashes) > 0 {
		for _, b := range m.TxHashes {
			l = len(b)
			n += 1 + l + sovReceipts(uint64(l))
		}
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovReceipts(uint64(l))
	}
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovReceipts(uint64(l))
	}
	return n
}

func (m *Receipt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sum != nil {
		n += m.Sum.Size()
	}
	return n
}

func (m *Receipt_AckTransactionBroadcast) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AckTransactionBroadcast != nil {
		l = m.AckTransactionBroadcast.Size()
		n += 1 + l + sovReceipts(uint64(l))
	}
	return n
}

func sovReceipts(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReceipts(x uint64) (n int) {
	return sovReceipts(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AckTransactionBroadcast) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReceipts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AckTransactionBroadcast: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AckTransactionBroadcast: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHashes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceipts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthReceipts
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthReceipts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHashes = append(m.TxHashes, make([]byte, postIndex-iNdEx))
			copy(m.TxHashes[len(m.TxHashes)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceipts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceipts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceipts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceipts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReceipts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReceipts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReceipts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReceipts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Receipt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReceipts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Receipt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Receipt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AckTransactionBroadcast", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReceipts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReceipts
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReceipts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AckTransactionBroadcast{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Receipt_AckTransactionBroadcast{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReceipts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReceipts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReceipts(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReceipts
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReceipts
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReceipts
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReceipts
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReceipts
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReceipts
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReceipts        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReceipts          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReceipts = fmt.Errorf("proto: unexpected end of group")
)
