// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cometbft/multiplex/v1/types.proto

package v1

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	v1 "github.com/ice-blockchain/cometbft/api/cometbft/p2p/v1"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MultiNetworkNodeInfo is the node information exchanged between two
// peers of a multi-network infra during the CometBFT P2P handshake.
type MultiNetworkNodeInfo struct {
	ProtocolVersion *v1.ProtocolVersion     `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	DefaultNodeID   string                  `protobuf:"bytes,2,opt,name=default_node_id,json=defaultNodeId,proto3" json:"default_node_id,omitempty"`
	ListenAddr      string                  `protobuf:"bytes,3,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Version         string                  `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Channels        []byte                  `protobuf:"bytes,5,opt,name=channels,proto3" json:"channels,omitempty"`
	Moniker         string                  `protobuf:"bytes,6,opt,name=moniker,proto3" json:"moniker,omitempty"`
	Other           v1.DefaultNodeInfoOther `protobuf:"bytes,7,opt,name=other,proto3" json:"other"`
}

func (m *MultiNetworkNodeInfo) Reset()         { *m = MultiNetworkNodeInfo{} }
func (m *MultiNetworkNodeInfo) String() string { return proto.CompactTextString(m) }
func (*MultiNetworkNodeInfo) ProtoMessage()    {}
func (*MultiNetworkNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_760696ebd5cddee0, []int{0}
}
func (m *MultiNetworkNodeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MultiNetworkNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MultiNetworkNodeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MultiNetworkNodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiNetworkNodeInfo.Merge(m, src)
}
func (m *MultiNetworkNodeInfo) XXX_Size() int {
	return m.Size()
}
func (m *MultiNetworkNodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiNetworkNodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MultiNetworkNodeInfo proto.InternalMessageInfo

func (m *MultiNetworkNodeInfo) GetProtocolVersion() *v1.ProtocolVersion {
	if m != nil {
		return m.ProtocolVersion
	}
	return nil
}

func (m *MultiNetworkNodeInfo) GetDefaultNodeID() string {
	if m != nil {
		return m.DefaultNodeID
	}
	return ""
}

func (m *MultiNetworkNodeInfo) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *MultiNetworkNodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *MultiNetworkNodeInfo) GetChannels() []byte {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *MultiNetworkNodeInfo) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *MultiNetworkNodeInfo) GetOther() v1.DefaultNodeInfoOther {
	if m != nil {
		return m.Other
	}
	return v1.DefaultNodeInfoOther{}
}

func init() {
	proto.RegisterType((*MultiNetworkNodeInfo)(nil), "cometbft.multiplex.v1.MultiNetworkNodeInfo")
}

func init() { proto.RegisterFile("cometbft/multiplex/v1/types.proto", fileDescriptor_760696ebd5cddee0) }

var fileDescriptor_760696ebd5cddee0 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6e, 0xa2, 0x50,
	0x14, 0xc6, 0xc1, 0xf1, 0xcf, 0xcc, 0x75, 0x8c, 0x33, 0xc4, 0x49, 0x88, 0x93, 0x20, 0x33, 0x49,
	0x13, 0x37, 0x85, 0x68, 0x57, 0x4d, 0xba, 0xd1, 0xb8, 0x69, 0x9a, 0xda, 0x86, 0x85, 0x8b, 0x6e,
	0x08, 0x70, 0x2f, 0x72, 0x23, 0xde, 0x73, 0x03, 0x57, 0xda, 0xbe, 0x45, 0x1f, 0xcb, 0xa5, 0xe9,
	0xaa, 0x2b, 0xd3, 0xe0, 0x8b, 0x34, 0x80, 0x12, 0xfb, 0x67, 0xc7, 0x77, 0xce, 0xef, 0xfb, 0xce,
	0x39, 0x00, 0xfa, 0xe7, 0xc1, 0x92, 0x08, 0xd7, 0x17, 0xe6, 0x72, 0x15, 0x0a, 0xca, 0x43, 0xf2,
	0x60, 0x26, 0x03, 0x53, 0x3c, 0x72, 0x12, 0x1b, 0x3c, 0x02, 0x01, 0xca, 0x9f, 0x03, 0x62, 0x94,
	0x88, 0x91, 0x0c, 0xba, 0x9d, 0x39, 0xcc, 0x21, 0x27, 0xcc, 0xec, 0xa9, 0x80, 0xbb, 0x7f, 0xcb,
	0x3c, 0x3e, 0xe4, 0x1f, 0x92, 0xfe, 0x3f, 0x57, 0x50, 0xe7, 0x3a, 0xcb, 0x98, 0x12, 0x71, 0x0f,
	0xd1, 0x62, 0x0a, 0x98, 0x5c, 0x32, 0x1f, 0x94, 0x2b, 0xf4, 0x2b, 0x27, 0x3c, 0x08, 0xed, 0x84,
	0x44, 0x31, 0x05, 0xa6, 0xca, 0xba, 0xdc, 0x6f, 0x0e, 0x75, 0xa3, 0x9c, 0xce, 0x87, 0xdc, 0x48,
	0x06, 0xc6, 0xed, 0x1e, 0x9c, 0x15, 0x9c, 0xd5, 0xe6, 0xef, 0x0b, 0xca, 0x39, 0x6a, 0x63, 0xe2,
	0x3b, 0xab, 0x50, 0xd8, 0x0c, 0x30, 0xb1, 0x29, 0x56, 0x2b, 0xba, 0xdc, 0xff, 0x31, 0xfe, 0x9d,
	0x6e, 0x7b, 0xad, 0x49, 0xd1, 0xca, 0x47, 0x4f, 0xac, 0x16, 0x3e, 0x92, 0x58, 0xe9, 0xa1, 0x66,
	0x48, 0x63, 0x41, 0x98, 0xed, 0x60, 0x1c, 0xa9, 0xdf, 0x32, 0x9b, 0x85, 0x8a, 0xd2, 0x08, 0xe3,
	0x48, 0x51, 0x51, 0xe3, 0xb0, 0x5f, 0x35, 0x6f, 0x1e, 0xa4, 0xd2, 0x45, 0xdf, 0xbd, 0xc0, 0x61,
	0x8c, 0x84, 0xb1, 0x5a, 0xd3, 0xe5, 0xfe, 0x4f, 0xab, 0xd4, 0x99, 0x6b, 0x09, 0x8c, 0x2e, 0x48,
	0xa4, 0xd6, 0x0b, 0xd7, 0x5e, 0x2a, 0x23, 0x54, 0x03, 0x11, 0x90, 0x48, 0x6d, 0xe4, 0xd7, 0x9e,
	0x7c, 0xba, 0xf6, 0x78, 0x5d, 0xe6, 0xc3, 0x4d, 0x06, 0x8f, 0xab, 0xeb, 0x6d, 0x4f, 0xb2, 0x0a,
	0xe7, 0x78, 0xb6, 0x4e, 0x35, 0x79, 0x93, 0x6a, 0xf2, 0x6b, 0xaa, 0xc9, 0x4f, 0x3b, 0x4d, 0xda,
	0xec, 0x34, 0xe9, 0x65, 0xa7, 0x49, 0x77, 0x17, 0x73, 0x2a, 0x82, 0x95, 0x9b, 0x65, 0x9a, 0xd4,
	0x23, 0xa7, 0x6e, 0x08, 0xde, 0xc2, 0x0b, 0x1c, 0xca, 0xcc, 0xf2, 0x2b, 0x39, 0x9c, 0x9a, 0x5f,
	0xfe, 0x02, 0x6e, 0x3d, 0x7f, 0xaf, 0x67, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x74, 0xef,
	0xf8, 0x22, 0x02, 0x00, 0x00,
}

func (m *MultiNetworkNodeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MultiNetworkNodeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MultiNetworkNodeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Other.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Channels) > 0 {
		i -= len(m.Channels)
		copy(dAtA[i:], m.Channels)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Channels)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ListenAddr) > 0 {
		i -= len(m.ListenAddr)
		copy(dAtA[i:], m.ListenAddr)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ListenAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DefaultNodeID) > 0 {
		i -= len(m.DefaultNodeID)
		copy(dAtA[i:], m.DefaultNodeID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DefaultNodeID)))
		i--
		dAtA[i] = 0x12
	}
	if m.ProtocolVersion != nil {
		{
			size, err := m.ProtocolVersion.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MultiNetworkNodeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProtocolVersion != nil {
		l = m.ProtocolVersion.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DefaultNodeID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ListenAddr)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Channels)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.Other.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MultiNetworkNodeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MultiNetworkNodeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MultiNetworkNodeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolVersion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProtocolVersion == nil {
				m.ProtocolVersion = &v1.ProtocolVersion{}
			}
			if err := m.ProtocolVersion.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultNodeID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultNodeID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListenAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListenAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channels", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channels = append(m.Channels[:0], dAtA[iNdEx:postIndex]...)
			if m.Channels == nil {
				m.Channels = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Other", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Other.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
